management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enable: true
    app:
      name: "Api de Cálculos"
      version: 1.0.0
      description: "Api responsável por gerenciar transações e cálculos"
    metrics:
      tags:
        application: api-calculos
  metrics:
    enable:
      all: true

springdoc:
  show-actuator: true